# 스케일 아웃 상황에서 랜덤하게 5만번 ~ 6만번 대의 포트번호를 부여 받을 수 있또록 명시적으로 작성하지 않음
server:
  port: 0

spring:
  application:
    name: 2nd-service
eureka:
  # 포트 번호가 동일하면 Eureka Server ui에서 구분되지 않으므로 별도의 instance id 부여
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    # Eureka Server에서 Service Registry를 가져오도록 설정
    fetch-registry: true
    # Eureka Server에 해당 인스턴스를 등록하도록 설정
    register-with-eureka: true
    service-url:
      # Eureka Server의 기본 URL 설정
      defaultZone: http://localhost:8761/eureka